services:
  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - ../.env.example
    ports:
      - "5434:5432"
    volumes:
      - booking_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: booking_redis

  booking:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: booking_app
    ports:
      - "8000:8000"
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env.example
    volumes:
      - ..:/app/
    depends_on:
      - db
      - redis

volumes:
  booking_data: